# These are supported funding model platforms

Support Project VIC International's Crimes Against Children Ontology Project via Give Lively: https://secure.givelively.org/donate/project-vic-international-inc/crimes-against-children-cac-ontology
